name: easylist2
description: A new Flutter project.
version: 1.0.0+1


environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^1.0.1
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/

  uses-material-design: true


  fonts:
    - family: Oswald
      fonts:
        - asset: assets/font/Oswald-Bold.ttf
          weight: 700
 

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true